//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOL.GreatOffice.Api.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_nb {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_nb() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IOL.GreatOffice.Api.Resources.SharedResources_nb", typeof(SharedResources_nb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Name_is_a_required_field {
            get {
                return ResourceManager.GetString("Name is a required field", resourceCulture);
            }
        }
        
        internal static string Start_is_a_required_field {
            get {
                return ResourceManager.GetString("Start is a required field", resourceCulture);
            }
        }
        
        internal static string Invalid_form {
            get {
                return ResourceManager.GetString("Invalid form", resourceCulture);
            }
        }
        
        internal static string One_or_more_fields_is_invalid {
            get {
                return ResourceManager.GetString("One or more fields is invalid", resourceCulture);
            }
        }
        
        internal static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid username or password", resourceCulture);
            }
        }
        
        internal static string One_or_more_validation_errors_occured {
            get {
                return ResourceManager.GetString("One or more validation errors occured", resourceCulture);
            }
        }
        
        internal static string Greatoffice_Email_Validation {
            get {
                return ResourceManager.GetString("Greatoffice Email Validation", resourceCulture);
            }
        }
        
        internal static string Reset_password___Greatoffice {
            get {
                return ResourceManager.GetString("Reset password - Greatoffice", resourceCulture);
            }
        }
        
        internal static string The_password_requires_6_or_more_characters_ {
            get {
                return ResourceManager.GetString("The password requires 6 or more characters.", resourceCulture);
            }
        }
        
        internal static string There_is_already_a_user_registered_with_username___username_ {
            get {
                return ResourceManager.GetString("There is already a user registered with username: {username}", resourceCulture);
            }
        }
        
        internal static string _username__does_not_look_like_a_valid_email {
            get {
                return ResourceManager.GetString("{username} does not look like a valid email", resourceCulture);
            }
        }
        
        internal static string Could_not_create_your_account__try_again_soon_ {
            get {
                return ResourceManager.GetString("Could not create your account, try again soon.", resourceCulture);
            }
        }
    }
}
