//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOL.GreatOffice.Api.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IOL.GreatOffice.Api.Resources.SharedResources_en", typeof(SharedResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Name_is_a_required_field {
            get {
                return ResourceManager.GetString("Name is a required field", resourceCulture);
            }
        }
        
        internal static string Start_is_a_required_field {
            get {
                return ResourceManager.GetString("Start is a required field", resourceCulture);
            }
        }
        
        internal static string Invalid_form {
            get {
                return ResourceManager.GetString("Invalid form", resourceCulture);
            }
        }
        
        internal static string One_or_more_validation_errors_occured {
            get {
                return ResourceManager.GetString("One or more validation errors occured", resourceCulture);
            }
        }
        
        internal static string One_or_more_fields_is_invalid {
            get {
                return ResourceManager.GetString("One or more fields is invalid", resourceCulture);
            }
        }
        
        internal static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid username or password", resourceCulture);
            }
        }
    }
}
